version: 2

references: 
  workspace_root: &workspace_root
    /tmp/workspace
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  buildapp:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm run test-cli
      - run: # run tests
          name: typescript build
          command: npm run build
      - save_cache: # save build
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./dist/

workflows:
    version: 2
    build-and-deploy:
        jobs:
        - buildapp